name: Build and Publish
on:
  push:
    branches:
      - master
      - 'release-*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_run:
    workflows: [Pull Translations from Transifex]
    types: [completed]
    branches:
      - master
      - 'release-*'
  workflow_dispatch:

jobs:
  build-publish-docker-helm:
    name: Build & Publish Docker Image & Helm Chart
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: package/helm/
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
          
      - name: Set env.ARTIFACT_VERSION
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Global Dependencies
        run: |
          npm install -g bower
          npm install -g grunt-cli
          gem install compass
          npm install --global yarn

      - name: Micro-frontends Setup and Build
        working-directory: micro-frontends
        env:
          CI: true
        run: |
          yarn install --frozen-lockfile
          yarn cache clean
          yarn build

      - name: Package UI
        run: |
          cd ui
          yarn cache clean
          chmod +x ./scripts/package.sh
          ./scripts/package.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: package/docker/Dockerfile
          push: true
          tags: venevital/bahmni-web:${{ env.ARTIFACT_VERSION }},venevital/bahmni-web:latest
